### ISSUE TITLE
twitch-integration-test

### ISSUE THREAD

**Issue by PaulieScanlon** [PaulieScanlon/mdx-embed#122]
Hooray 🎉 thanks for your interest in [MDX Embed](https://mdx-embed.com) 

If you'd like to contribute by writing this test please have a read of: 

- The [Umbrella Issue](https://github.com/PaulieScanlon/mdx-embed/issues/71) 
- The [Acceptance Criteria](https://github.com/PaulieScanlon/mdx-embed/issues/71#acceptance-criteria) for **Integration Tests**

**Comment by PaulieScanlon** [comment]
This integration test might be a little tricky because the Twitch component requires the `parent` prop. 

eg.

```javascript
<Twitch twitchId="679474192" parent="www.mdx-embed.com" />
```

The `parent` prop is what Twitch uses to determine where the Twitch player is making the request from. There's more details [here](https://discuss.dev.twitch.tv/t/twitch-embedded-player-migration-timeline-update/25588) from an update in June 2020

Pay particular attention to this bit 👇

> Who will be affected by these changes?
Any third-party site or developer currently using embedded Twitch features (chat 15, video 81 including Clips, and everything 48).

We introduced the `parent` prop in the old repo [here](https://github.com/PaulieScanlon/gatsby-mdx-embed/pull/18)


You'll see from the above example the `parent` prop is set to `www.mdx-embed.com` and this is so when we deploy the Storybook docs site the Twitch player works.

However, when you run Storybook locally `yarn storybook` you'll notice the Twitch player fails to load. This is because its "parent" is now `localhost:6006`

This will also be the case when running `cy:test` locally and when Cypress tests are run through the CI.

Interestingly this Twitch `parent` issue is the exact reason I decided we needed integration tests as the unit tests won't catch issues such as this. The main approach for our Hactoberfest integration test is to ensure third party embed scripts actually load the component and we are able to find provider specific DOM nodes in the DOM. 

Ok phew!

There's a few things we'll need to investigate in order to get this integration test working. Here's an order of investigation that might be helpful.

- Establish what the `parent` url needs to be set to in order for Twitch to load when running `yarn storybook` locally.
  - localhost:6006/
  - http://localhost:6006/
  - etc

- Establish how to set Storybook env. I think using something like this will work
  - `"storybook-blah-1": "NODE_ENV=production start-storybook"`
  - `"storybook-blah-1": "NODE_ENV=development start-storybook"`

We _might_ need additional scripts in `package.json` to ensure the correct `env` is set, although I think Storybook might do this already. running `storybook:build` might help to understand what the `env` is

Once we know how to ensure which `env` Storybook is running in we can probably use the `env` to determine the `parent` url

The environment uses are:
-  mdx-embed.com => production
- local `yarn storybook` => development
- CI `yarn cy:test` => development


If we then arrive at a point where we can use the `env` to switch the `parent` prop from `www.mdx-embed.com` to `localhost:6006` we might need to investigate the "Show code" snippet in the docs.


What **wouldn't** be so great would be if the story had a code snippet like this 👇

```javascript
<Twitch twitchId="679474192" parent={process.env.TWITCH_PARENT} />
```

... but if that's what we need to do then perhaps we can add some additional detail to the story description explaining what `process.env.TWITCH_PARENT` actually is.

Happy to work on this with you, and if you have any questions let me know - @PaulieScanlon

**Comment by yenly** [comment]
It sounds complicated, but I would like to give it a go. 😅 I want to do some homework on it first. Would like to on pair this if possible. I will see who's interested in party corgi since this sounds like a good learning experience.

**Comment by will-t-harris** [comment]
Hi @yenly, I reached out in party-corgi but also wanted to connect here. I'd be interested in pairing on this issue if you're still looking for someone.

I have a bit of experience with Cypress and would be excited to learn more. Let me know if you're interested! :+1:

**Comment by PaulieScanlon** [comment]
Hey @will-t-harris thanks so much for getting involved. I'll be on hand if you two have any questions. This one is a bit of a tricky one so if it's feeling like too much work its totally fine to hand it back over to me. I'm really excited to see the collaboration though so if you both do have time i'd love to see this completed, but completely understand if not.

**Comment by will-t-harris** [comment]
Hi there @PaulieScanlon :wave: 

@yenly and I spent some time pairing on this test this afternoon and have some questions. 

*(Also Yenly, feel free to add anything that I missed here. I took some brief notes after our pairing session, but have been pretty busy since and may have lost some context :sweat_smile: )*

## Here's what we did

We first wanted to see what happened when we hard-coded different values into the `Twitch` component, so we:

- Went into the `twitch.stories.mdx` file in `docs/pages/components/`
- Changed the `parent` prop to `localhost:6006`, `http://localhost:6006/`, `127.0.0.1:6006/`, and the IP address that storybook was running on locally (I believe it was `192.198.4.49:6006`

These changes all appeared to allow the response from Twitch to render, but for each it displayed an error pointing to an 'invalid character in the `parent` parameter.' :thinking: 

The error also pointed us at [this documentation](https://dev.twitch.tv/docs/embed/video-and-clips/)

We read through the Twitch thread you posted above that talks about changes to the Twitch embed migration from this summer. That thread made it sound like there was an issue with embeds that were not served via `https`, but that the issue was resolved to allow `localhost` embeds sometime in June.

If you have any suggestions on potential directions for us to investigate moving forward, we're all ears! :+1:

**Comment by will-t-harris** [comment]
Hi there @PaulieScanlon :wave: 

@Yenly and I spent some time pairing on this test this afternoon and have some questions. 

(Also Yenly, feel free to add anything that I missed here. I took some brief notes after our pairing session, but have been pretty busy since and may have lost some context :sweat_smile: )

## Here's what we did

We first wanted to see what happened when we hard-coded different values into the Twitch component, so we:

- Went into the twitch.stories.mdx file in docs/pages/components/
- Changed the parent prop to localhost:6006, http://localhost:6006/, 127.0.0.1:6006/, and the IP address that storybook was running on locally (I believe it was 192.198.4.49:6006

These changes all appeared to allow the response from Twitch to render, but for each it displayed an error pointing to an 'invalid character in the parent parameter.' :thinking: 

The error also pointed us at [this documentation](https://dev.twitch.tv/docs/embed/video-and-clips/)

We read through the Twitch thread you posted above that talks about changes to the Twitch embed migration from this summer. That thread made it sound like there was an issue with embeds that were not served via https, but that the issue was resolved to allow localhost embeds sometime in June.

If you have any suggestions on potential directions for us to investigate moving forward, we're all ears! :thumbsup:

**Comment by PaulieScanlon** [comment]
Hi both, thanks for looking into this. I had a quick google and it looks like parent is without port.

This should work

```javascript
<Twitch twitchId="783572188" parent="localhost" />
```

FYI the id's that i was using in the examples don't seem to be available online anymore so perhaps we'll need to update the docs with an id of a video that is still available

**Comment by will-t-harris** [comment]
That does work, thanks! Now just to investigate how to swap out that prop value depending on the env.

Should we include in our PR a video id that is still available? I suspect that you'll continue to run into this issue periodically since twitch videos aren't permanent (as far as I understand).

**Comment by PaulieScanlon** [comment]
@will-t-harris  Hey, yes please, update your PR to include a working video. 

I think as and when Twitch videos disappear this integration test will fail so we'll be able to catch them prior to publishing the docs.

Here's a link to [Storybook environment-variables](https://storybook.js.org/docs/react/configure/environment-variables) i think this will be somewhat related to what we need.

**Comment by yenly** [comment]
I hardcoded parent to use localhost and got tests to pass. Working on setting env part and I am a bit confused about how. Will come back to it later tonight.

**Comment by PaulieScanlon** [comment]
Hey @yenly try this:

- Go to `twitch.tsx`, before the `return` pop this in `console.log(' process.env.NODE_ENV: ', process.env.NODE_ENV);`
- Start Storybook `yarn storybook` - have a look at your console, you should see `process.env.NODE_ENV:  development`

I know that when we run `storybook build` Storybook is kicked into "production" mode so this will give us enough to create a ternary condition for the `parent` url.

- Go back to `twitch.tsx` and make the below change to the `baseUrl` const

```diff
 - const baseUrl = `https://player.twitch.tv/?autoplay=${autoPlay}&t=${h}h${m}m${s}s&parent=${parent}`;
 + const baseUrl = `https://player.twitch.tv/?autoplay=${autoPlay}&t=${h}h${m}m${s}s&parent=${
 +  process.env.NODE_ENV === 'development' ? 'localhost' : parent
 + }`;
```
If we catch the `NODE_ENV` here in the component the code snippet in "Show Code" in storybook will always say 'www.mdx-embed.com' which is great, and secretly under the hood we're able to use the `NODE_ENV` to change the `parent` prop from whatever is provided by the prop to `localhost`

I think this will be particularly useful for anyone using MDX Embed because when they run it locally their `NODE_ENV` will most likely be "development" e.g `localhost` and when they run in "production" the `parent` prop will be whatever their blog or site URL is which they'll pas in from the component usage e.g

```javascript
 <Twitch twitchId="679474192" parent="www.paulie.dev" />
```
See how you get on with this and please do let me know if you need any more help.


The only thing i don't know at the moment is if the `NODE_ENV` remains as "development" when we run the tests through Circle CI... 

if the tests pass when you create your PR it would prove it does, if they fail i'll investigate and see what `NODE_ENV` Circle sets.

Make sense?

**Comment by yenly** [comment]
@PaulieScanlon It worked! Thank you so much for the explanation and your guidance. I was on the wrong path of thinking I might need to install dotenv to set the storybook env when as a first step, I tried adding this in ```"storybook:test": "set STORYBOOK_TWITCH_PARENT=local && yarn workspace docs storybook",``` and it didn't work. Anyhow, will be sending PR over soon.

**Comment by PaulieScanlon** [comment]
@yenly Hooray!!! So pleased that worked! I'll look forward to the PR! 

Nice work!
